import type { LegacyViewFamilyDefinition, ViewGraphOperation, ViewSpec } from "./spec.js";
import { legacyViewFamilyToSpec, normalizeViewSpec } from "./spec.js";

export const DEFAULT_VIEW_GRAPH_OPERATIONS: readonly ViewGraphOperation[] = [
  "create",
  "update",
  "fork",
  "archive",
  "merge",
  "split",
  "promote",
  "demote",
  "supersede",
  "diff",
  "retain",
  "retire",
];

// Legacy catalog entries not yet superseded by a named ViewSpec above.
// These are kept for backwards compatibility with older UI and server routes.
const LEGACY_CATALOG_DEFINITIONS: readonly LegacyViewFamilyDefinition[] = [
  { view_type: "evidence", label: "EvidenceView", purpose: "Normalized evidence from raw observations.", category: "semantic", producers: ["compiler"], default_page_size: 120 },
  { view_type: "visual_frame", label: "VisualFrameView", purpose: "Screen semantics compressed from visual evidence.", category: "semantic", producers: ["compiler"], default_page_size: 80 },
  { view_type: "audio", label: "AudioView", purpose: "Speech or transcript semantics compressed from audio evidence.", category: "semantic", producers: ["compiler"], default_page_size: 60 },
  { view_type: "activity", label: "ActivityView", purpose: "Time-based activity chunks built from evidence.", category: "semantic", producers: ["compiler"], default_page_size: 120 },
  { view_type: "activity.episode", label: "Activity Episode", purpose: "Continuous user-understandable activity segment grouped from stable app or page observations.", category: "semantic", producers: ["compiler"], default_page_size: 80 },
  { view_type: "activity_block", label: "ActivityBlockView", purpose: "Short work blocks synthesized from visual, audio, and activity views.", category: "semantic", producers: ["compiler"], default_page_size: 60 },
  { view_type: "proposal", label: "ProposalView", purpose: "Control view that proposes which downstream views should exist.", category: "semantic", producers: ["compiler"], default_page_size: 80 },
  { view_type: "resource", label: "ResourceView", purpose: "Reusable material observed in the user's workflow.", category: "semantic", producers: ["compiler", "manual", "agent"], default_page_size: 60, manual_create: true },
  { view_type: "intent", label: "IntentView", purpose: "Current or inferred goal signal.", category: "semantic", producers: ["compiler", "manual", "agent"], default_page_size: 60, manual_create: true },
  { view_type: "workflow", label: "WorkflowView", purpose: "Structured work session composed from activities, resources, and intents.", category: "semantic", producers: ["compiler", "manual", "agent"], default_page_size: 60, manual_create: true },
  { view_type: "memory", label: "MemoryView", purpose: "Durable agent/app-consumable memory.", category: "memory", producers: ["compiler", "program", "manual", "agent"], default_page_size: 60, manual_create: true },
  { view_type: "thread.active_work", label: "Active Work", purpose: "Current work focus from project/context signals.", category: "project", producers: ["program"], default_page_size: 60 },
  { view_type: "project.current_context", label: "Project Context", purpose: "Current project state and relevant context.", category: "project", producers: ["program", "manual"], default_page_size: 60, manual_create: true },
  { view_type: "brief.research", label: "Research Brief", purpose: "Research synthesis for a topic, resource, or active work thread.", category: "ambient", producers: ["program", "agent", "manual"], default_page_size: 60, manual_create: true, aliases: ["research.brief"], graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS },
  { view_type: "brief.background_research", label: "Background Research", purpose: "Background research prepared from proactive task delegation.", category: "ambient", producers: ["agent", "runtime"], default_page_size: 80 },
  { view_type: "advice.research", label: "Research Advice", purpose: "Lightweight research suggestion surfaced at the right time.", category: "ambient", producers: ["program"], default_page_size: 80 },
  { view_type: "advice.writing_assist", label: "Writing Assist", purpose: "Inline-safe writing advice for active text editing.", category: "ambient", producers: ["program", "agent"], default_page_size: 80, aliases: ["writing.advice"], graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS },
  { view_type: "task.background_research", label: "Research Task", purpose: "Proactive background research task for an agent runtime.", category: "ambient", producers: ["program", "manual"], default_page_size: 80, manual_create: true },
  { view_type: "draft.writing_continuation", label: "Writing Draft", purpose: "Editable writing continuation or draft.", category: "ambient", producers: ["program", "agent"], default_page_size: 80 },
  { view_type: "opportunity.tool", label: "Tool Opportunity", purpose: "Detected workflow improvement or small-tool opportunity.", category: "ambient", producers: ["program", "manual"], default_page_size: 80, manual_create: true },
  { view_type: "draft.tool_prototype", label: "Tool Prototype", purpose: "Prototype plan for a workflow-improving tool.", category: "ambient", producers: ["agent", "program"], default_page_size: 80 },
  { view_type: "tool.prototype_artifact", label: "Tool Artifact", purpose: "Inspectable sandbox artifact compiled from a tool prototype.", category: "runtime", producers: ["runtime"], default_page_size: 80 },
  { view_type: "work_thread", label: "Work Thread", purpose: "Runtime-maintained candidate thread index.", category: "runtime", producers: ["runtime"], default_page_size: 60 },
  { view_type: "timeline.activity", label: "Activity Timeline", purpose: "Runtime activity timeline for UI and debugging.", category: "runtime", producers: ["runtime"], default_page_size: 60 },
  { view_type: "project_timeline", label: "Project Timeline", purpose: "Project-scoped timeline with records, events, and work threads.", category: "runtime", producers: ["runtime"], default_page_size: 60 },
  { view_type: "summary.project_work_episode", label: "Project Episode", purpose: "Episode summary for a work thread.", category: "runtime", producers: ["runtime"], default_page_size: 60 },
];

const COMMON_SPEC_METADATA = {
  viewgraph: {
    doctrine: "Views arise from observations and can be forked, rewritten, merged, split, promoted, demoted, retained, or retired as future-task needs change.",
    source: "docs/view-first-proactive-agent-os.md",
  },
};

export const CORE_VIEW_SPECS: readonly ViewSpec[] = [
  {
    view_type: "state.surface",
    title: "Current Surface",
    purpose: "Ephemeral current context fused from browser, editor, media, and screen observations.",
    lifecycle: "ephemeral",
    subject: {
      description: "The user's currently visible or focused work surface. Subject metadata remains open.",
      examples: [{ type: "browser_page", title: "Docs tab" }, { type: "editor", title: "Focused text input" }],
    },
    producers: [{ id: "processor.surface_state", kind: "processor" }],
    consumes: {
      observations: [
        "observation.browser_*",
        "observation.editor.*",
        "observation.youtube.*",
        "observation.screenpipe_*",
      ],
    },
    default_query: { view_types: ["state.surface"], limit: 1 },
    tags: ["surface", "current", "core"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "core", default_page_size: 40 },
    examples: [{
      view_type: "state.surface",
      title: "Current surface: browser page",
      content: {
        surface_kind: "browser_page",
        active_url: "https://example.com",
        selected_text: "Highlighted text",
      },
    }],
  },
  {
    view_type: "work.focus_set",
    title: "Work Focus Set",
    purpose: "Recent active work lanes produced by scheduled hybrid routing before project/research/memory updates.",
    lifecycle: "session",
    subject: {
      description: "A recent time window of user work that may contain multiple simultaneous lanes.",
      examples: [{ window_minutes: 90, active_lanes: ["project:/Users/junjie/info", "topic:midscene"] }],
    },
    producers: [{ id: "processor.work_router_batch", kind: "processor" }],
    consumes: {
      observations: ["observation.route_candidate", "observation.*"],
      views: ["state.surface"],
    },
    default_query: { view_types: ["work.focus_set"], limit: 5 },
    tags: ["work", "router", "focus", "hybrid"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "core", default_page_size: 40 },
    examples: [{
      view_type: "work.focus_set",
      content: {
        active_lanes: [
          { lane_key: "project:/Users/junjie/info", lane_kind: "project", attention_share: 0.78 },
          { lane_key: "topic:midscene", lane_kind: "topic", attention_share: 0.16 },
        ],
      },
    }],
  },
  {
    view_type: "project.current",
    title: "Project Current",
    purpose: "Current project identity, active focus, key context, and supporting sources.",
    lifecycle: "project",
    subject: {
      description: "Open project metadata such as name, path, repo, issue, or user-defined labels.",
      examples: [{ name: "info", path: "/Users/junjie/info" }],
    },
    producers: [{ id: "processor.project_current", kind: "processor" }, { id: "manual.project_note", kind: "manual" }],
    consumes: {
      observations: ["observation.codex.message", "observation.claude.message", "observation.browser_page_snapshot", "observation.local_project"],
      views: ["work.focus_set", "project.decisions", "project.tasks", "project.inbox"],
    },
    default_query: { view_types: ["project.current"], limit: 5 },
    tags: ["project", "dogfood"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "project", default_page_size: 40 },
    examples: [{
      view_type: "project.current",
      content: {
        focus: "Design View-first proactive agent OS",
        open_questions: ["How should new view families be added?"],
      },
    }],
  },
  {
    view_type: "project.inbox",
    title: "Project Inbox",
    purpose: "Project-relevant unresolved observations, resources, questions, and agent outputs awaiting triage.",
    lifecycle: "project",
    subject: {
      description: "Open project or work context metadata.",
      examples: [{ name: "info" }],
    },
    producers: [{ id: "processor.project_inbox", kind: "processor" }],
    consumes: {
      observations: ["observation.browser_page_snapshot", "observation.codex.message"],
      views: ["brief.research", "advice.writing_assist", "research.brief", "writing.advice"],
    },
    default_query: { view_types: ["project.inbox"], limit: 20 },
    tags: ["project", "inbox"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "project", default_page_size: 40 },
    examples: [{
      view_type: "project.inbox",
      content: { items: [{ title: "Review ViewSpec API", reason: "Blocks CLI and processor reporting" }] },
    }],
  },
  {
    view_type: "project.memory",
    title: "Project Memory",
    purpose: "Longer-lived project-specific principles, decisions, constraints, and recurring patterns.",
    lifecycle: "long_term",
    subject: {
      description: "Project identity remains metadata, not a core object.",
      examples: [{ name: "info" }],
    },
    producers: [{ id: "processor.project_memory", kind: "processor" }, { id: "manual.project_memory", kind: "manual" }],
    consumes: {
      views: ["project.decisions", "memory.workflow_patterns"],
      observations: ["feedback.output.edited"],
    },
    default_query: { view_types: ["project.memory"], limit: 20 },
    tags: ["project", "memory"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "memory", default_page_size: 40, manual_create: true },
    examples: [{
      view_type: "project.memory",
      content: { principles: ["Core owns protocols, not categories."] },
    }],
  },
  {
    view_type: "project.tasks",
    title: "Project Tasks",
    purpose: "Actionable project work items derived from conversations, issues, plans, and agent outputs.",
    lifecycle: "project",
    producers: [{ id: "processor.project_tasks", kind: "processor" }],
    consumes: { views: ["project.current", "project.inbox"], observations: ["observation.codex.message"] },
    default_query: { view_types: ["project.tasks"], limit: 20 },
    tags: ["project", "tasks"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "project", default_page_size: 40 },
    examples: [{
      view_type: "project.tasks",
      content: { tasks: [{ title: "Implement mf view CLI", status: "open" }] },
    }],
  },
  {
    view_type: "project.decisions",
    title: "Project Decisions",
    purpose: "Project decisions with rationale, source context, and open consequences.",
    lifecycle: "project",
    producers: [{ id: "processor.project_decision_extractor", kind: "processor" }, { id: "manual.project_decision", kind: "manual" }],
    consumes: { observations: ["observation.codex.message", "observation.claude.message"], views: ["project.current"] },
    default_query: { view_types: ["project.decisions"], limit: 20 },
    tags: ["project", "decisions"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "project", default_page_size: 40, manual_create: true },
    examples: [{
      view_type: "project.decisions",
      content: { decisions: [{ title: "Project is a built-in view family, not a kernel object.", source_count: 3 }] },
    }],
  },
  {
    view_type: "agent.task_list",
    title: "Agent Task List",
    purpose: "Unified queue surface for slow AgentTask work handled by Claude Code, Codex, ACP, or local adapters.",
    lifecycle: "session",
    producers: [{ id: "runtime.agent_task_list", kind: "runtime" }],
    consumes: { views: ["task.background_research"] },
    default_query: { view_types: ["agent.task_list"], limit: 1 },
    tags: ["agent", "tasks", "queue"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "ambient", default_page_size: 20 },
    examples: [{ view_type: "agent.task_list", content: { item_count: 2, counts: { queued: 1, completed: 1 }, items: [] } }],
  },
  {
    view_type: "view.promotion_candidates",
    title: "View Promotion Candidates",
    purpose: "Task-discovery output that proposes which Views or processors should be created, updated, combined, retired, or promoted.",
    lifecycle: "session",
    subject: {
      description: "A recent observation/view/event window analyzed for future-search compression opportunities.",
      examples: [{ window_minutes: 720, candidates: ["create_view", "combine_views", "retire_view", "create_processor"] }],
    },
    producers: [{ id: "processor.view_promotion_engine", kind: "processor" }],
    consumes: {
      observations: ["observation.*", "feedback.*"],
      views: ["*"],
    },
    default_query: { view_types: ["view.promotion_candidates"], limit: 10 },
    tags: ["viewgraph", "promotion", "task-discovery", "adaptive-memory"],
    graph_operations: ["create", "update", "archive", "fork", "promote", "demote", "retain", "retire"],
    metadata: { ...COMMON_SPEC_METADATA, category: "runtime", default_page_size: 30 },
    examples: [{
      view_type: "view.promotion_candidates",
      content: {
        candidates: [
          { action: "create_view", target_view_type: "research.failure", reason: "Repeated failure evidence would reduce future debugging search." },
          { action: "create_processor", target_processor_id: "processor.failure_miner", reason: "No registered processor produces research.failure." },
        ],
      },
    }],
  },
  {
    view_type: "memory.daily",
    title: "Daily Memory",
    purpose: "Editable markdown-backed daily memory summarizing one calendar day's work, decisions, active projects, useful context, and notable evidence.",
    lifecycle: "long_term",
    subject: {
      description: "One local calendar day of user work and context.",
      examples: [{ date: "2026-06-17", timezone: "Asia/Shanghai" }],
    },
    producers: [
      { id: "processor.memory_daily_update", kind: "processor" },
      { id: "manual.memory_daily_edit", kind: "manual" },
      { id: "agent.memory_daily_edit", kind: "agent" },
    ],
    storage: {
      kind: "markdown",
      content_key: "markdown",
      path_template: "memory/daily/{date}.md",
      description: "Canonical daily memory body lives as markdown, with path and summary mirrored in View content.",
    },
    consumes: {
      observations: ["observation.*", "feedback.*"],
      views: ["state.surface", "work.focus_set", "project.current", "timeline.activity"],
    },
    default_query: { view_types: ["memory.daily"], limit: 14 },
    tags: ["memory", "daily", "markdown", "core"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "memory", default_page_size: 30, manual_create: true },
    examples: [{
      view_type: "memory.daily",
      content: {
        date: "2026-06-17",
        markdown_path: "memory/daily/2026-06-17.md",
        summary: "Worked on Info view unification and agent-facing CLI/view doctrine.",
      },
    }],
  },
  {
    view_type: "memory.profile",
    title: "Memory Profile",
    purpose: "Editable markdown-backed durable user profile derived from daily memories and explicit feedback.",
    lifecycle: "long_term",
    subject: { description: "Open user/profile subject metadata.", examples: [{ type: "user" }] },
    producers: [
      { id: "processor.memory_profile_update", kind: "processor" },
      { id: "manual.memory_profile_edit", kind: "manual" },
      { id: "agent.memory_profile_edit", kind: "agent" },
    ],
    storage: {
      kind: "markdown",
      content_key: "markdown",
      path_template: "memory/profile/{subject}.md",
      description: "Canonical profile body lives as editable markdown, with durable facts mirrored in View content.",
    },
    consumes: { observations: ["feedback.*"], views: ["memory.daily"] },
    default_query: { view_types: ["memory.profile"], limit: 5 },
    tags: ["memory", "profile", "markdown", "core"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "memory", default_page_size: 30, manual_create: true },
    examples: [{ view_type: "memory.profile", content: { markdown_path: "memory/profile/user.md", summary: "Prefers architecture-first, issue-managed execution." } }],
  },
  {
    view_type: "memory.preferences",
    title: "Memory Preferences",
    purpose: "Stable user preferences that should change future surfacing, routing, and agent behavior.",
    lifecycle: "long_term",
    subject: { description: "Preference subject can be user, project, UI surface, agent, or any open string.", examples: [{ type: "user" }] },
    producers: [{ id: "processor.memory_profile_update", kind: "processor" }, { id: "manual.memory_preference", kind: "manual" }],
    consumes: { observations: ["feedback.view.dismissed", "feedback.output.edited", "observation.codex.message"] },
    default_query: { view_types: ["memory.preferences"], limit: 20 },
    tags: ["memory", "preferences"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "memory", default_page_size: 40, manual_create: true },
    examples: [{ view_type: "memory.preferences", content: { preference: "Prefer inbox/side-panel over intrusive popups.", evidence_count: 4 } }],
  },
  {
    view_type: "memory.workflow_patterns",
    title: "Memory Workflow Patterns",
    purpose: "Repeated work patterns that future agents can reuse or automate.",
    lifecycle: "long_term",
    subject: { description: "Workflow pattern subject metadata is open.", examples: [{ type: "coding_workflow" }] },
    producers: [{ id: "processor.workflow_pattern_miner", kind: "processor" }],
    consumes: { observations: ["observation.codex.message", "feedback.automation_result"], views: ["automation.outcome", "project.tasks"] },
    default_query: { view_types: ["memory.workflow_patterns"], limit: 20 },
    tags: ["memory", "workflow"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "memory", default_page_size: 40, manual_create: true },
    examples: [{ view_type: "memory.workflow_patterns", content: { pattern: "Plan with issues, branch, PR, then merge." } }],
  },
  {
    view_type: "memory.skill_gaps",
    title: "Memory Skill Gaps",
    purpose: "Longer-lived areas where the user repeatedly needs support or review.",
    lifecycle: "long_term",
    subject: { description: "Skill or learning subject metadata is open.", examples: [{ type: "language_learning" }] },
    producers: [{ id: "processor.skill_gap_miner", kind: "processor" }],
    consumes: { views: ["learning.review_queue", "learning.youtube_fragment"], observations: ["feedback.review_result"] },
    default_query: { view_types: ["memory.skill_gaps"], limit: 20 },
    tags: ["memory", "learning"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "memory", default_page_size: 40, manual_create: true },
    examples: [{ view_type: "memory.skill_gaps", content: { skill: "English listening fragments", evidence_count: 4 } }],
  },
  {
    view_type: "memory.agent_collaboration_style",
    title: "Memory Agent Collaboration Style",
    purpose: "How the user wants agents to plan, communicate, ask, and act.",
    lifecycle: "long_term",
    subject: { description: "Agent collaboration subject metadata is open.", examples: [{ type: "agent_collaboration" }] },
    producers: [{ id: "processor.agent_collaboration_style", kind: "processor" }],
    consumes: { observations: ["feedback.output.edited", "observation.codex.message"] },
    default_query: { view_types: ["memory.agent_collaboration_style"], limit: 20 },
    tags: ["memory", "agent"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "memory", default_page_size: 40, manual_create: true },
    examples: [{ view_type: "memory.agent_collaboration_style", content: { style: "Challenge weak assumptions; keep momentum." } }],
  },
  {
    view_type: "agent.case_memory",
    title: "Agent Case Memory",
    purpose: "Reusable agent execution cases, tool outcomes, and collaboration lessons for future automation.",
    lifecycle: "long_term",
    subject: { description: "Agent/task/capability subject metadata is open.", examples: [{ type: "agent_case" }] },
    producers: [{ id: "processor.memory_gate", kind: "processor" }, { id: "manual.agent_case_memory", kind: "manual" }],
    consumes: { observations: ["feedback.automation_result", "feedback.output.edited"], views: ["memory.daily", "automation.outcome"] },
    default_query: { view_types: ["agent.case_memory"], limit: 20 },
    tags: ["memory", "agent", "case"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "memory", default_page_size: 40, manual_create: true },
    examples: [{ view_type: "agent.case_memory", content: { case: "Use DOM tools before vision fallback on current Chrome pages." } }],
  },
  {
    view_type: "learning.youtube_fragment",
    title: "Learning YouTube Fragment",
    purpose: "Timestamped caption or playback fragment that can become review material.",
    lifecycle: "session",
    subject: { description: "Any video segment; no core enum is required.", examples: [{ type: "video", title: "Agent skills talk" }] },
    producers: [{ id: "processor.youtube_learning", kind: "processor" }],
    consumes: { observations: ["observation.youtube.caption_state", "observation.youtube.caption_fragment", "observation.youtube.comprehension_gap"] },
    default_query: { view_types: ["learning.youtube_fragment"], limit: 50 },
    tags: ["learning", "youtube", "scenario"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "learning", default_page_size: 50 },
    examples: [{ view_type: "learning.youtube_fragment", content: { start_seconds: 120, end_seconds: 146, caption_text: "Example caption text." } }],
  },
  {
    view_type: "learning.review_queue",
    title: "Learning Review Queue",
    purpose: "Prioritized review queue generated from YouTube fragments and difficult segments.",
    lifecycle: "session",
    subject: { description: "A list of YouTube fragments and difficult segments to review.", examples: [{ type: "review_queue", count: 5 }] },
    producers: [{ id: "processor.youtube_learning", kind: "processor" }],
    consumes: {
      views: [
        "learning.youtube_fragment",
        "memory.language.difficult_segments",
      ],
    },
    default_query: { view_types: ["learning.review_queue"], limit: 10 },
    tags: ["learning", "youtube", "review"],
    aliases: ["app.language.review_queue"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "learning", default_page_size: 20 },
    examples: [{ view_type: "learning.review_queue", content: { item_count: 5, items: [] } }],
  },
  {
    view_type: "memory.language.difficult_segments",
    title: "Difficult Language Segments",
    purpose: "Segments marked as difficult during YouTube language learning, stored for targeted review.",
    lifecycle: "long_term",
    subject: { description: "Difficult video segments.", examples: [{ type: "difficult_segment", video_id: "abc123", start: 120 }] },
    producers: [{ id: "processor.youtube_learning", kind: "processor" }],
    consumes: { views: ["learning.youtube_fragment"] },
    default_query: { view_types: ["memory.language.difficult_segments"], limit: 50 },
    tags: ["memory", "language", "difficult_segments"],
    graph_operations: DEFAULT_VIEW_GRAPH_OPERATIONS,
    metadata: { ...COMMON_SPEC_METADATA, category: "memory", default_page_size: 50, manual_create: true },
    examples: [{ view_type: "memory.language.difficult_segments", content: { video_id: "abc123", start_seconds: 120, end_seconds: 135, difficulty_reason: "fast speech" } }],
  },
];

const CORE_VIEW_TYPES = new Set(CORE_VIEW_SPECS.map(s => s.view_type));

export const LEGACY_VIEW_SPECS: readonly ViewSpec[] = LEGACY_CATALOG_DEFINITIONS
  .filter(d => !CORE_VIEW_TYPES.has(d.view_type))
  .map(legacyViewFamilyToSpec);

export function builtinViewSpecs(): ViewSpec[] {
  return [...CORE_VIEW_SPECS, ...LEGACY_VIEW_SPECS].map(normalizeViewSpec);
}
