import type { ViewSpec } from "./spec.js";

export const CORE_VIEW_SPECS: readonly ViewSpec[] = [
  {
    view_type: "state.surface",
    title: "Current Surface",
    purpose: "Ephemeral current context fused from browser, editor, media, and screen observations.",
    lifecycle: "ephemeral",
    subject: {
      description: "The user's currently visible or focused work surface. Subject metadata remains open.",
      examples: [{ type: "browser_page", title: "Docs tab" }, { type: "editor", title: "Focused text input" }],
    },
    producers: [{ id: "processor.surface_state", kind: "processor" }],
    consumes: {
      observations: [
        "observation.browser_*",
        "observation.editor.*",
        "observation.youtube.*",
        "observation.screenpipe_*",
      ],
    },
    default_query: { view_types: ["state.surface"], limit: 1 },
    tags: ["surface", "current", "core"],
    examples: [{
      view_type: "state.surface",
      title: "Current surface: browser page",
      content: {
        surface_kind: "browser_page",
        active_url: "https://example.com",
        selected_text: "Highlighted text",
      },
    }],
  },
  {
    view_type: "project.current",
    title: "Project Current",
    purpose: "Current project state, active focus, key context, and next useful agent context.",
    lifecycle: "project",
    subject: {
      description: "Open project metadata such as name, path, repo, issue, or user-defined labels.",
      examples: [{ name: "info", path: "/Users/junjie/info" }],
    },
    producers: [{ id: "processor.project_current", kind: "processor" }, { id: "manual.project_note", kind: "manual" }],
    consumes: {
      observations: ["observation.codex.message", "observation.claude.message", "observation.browser_page_snapshot", "observation.local_project"],
      views: ["project.decisions", "project.tasks", "project.inbox"],
    },
    default_query: { view_types: ["project.current"], limit: 5 },
    tags: ["project", "dogfood"],
    examples: [{
      view_type: "project.current",
      content: {
        focus: "Design View-first proactive agent OS",
        open_questions: ["How should new view families be added?"],
        next_actions: ["Create ViewSpec registry"],
      },
    }],
  },
  {
    view_type: "project.inbox",
    title: "Project Inbox",
    purpose: "Project-relevant unresolved observations, resources, questions, and agent outputs awaiting triage.",
    lifecycle: "project",
    subject: {
      description: "Open project or work context metadata.",
      examples: [{ name: "info" }],
    },
    producers: [{ id: "processor.project_inbox", kind: "processor" }],
    consumes: {
      observations: ["observation.browser_page_snapshot", "observation.codex.message"],
      views: ["research.brief", "writing.advice"],
    },
    default_query: { view_types: ["project.inbox"], limit: 20 },
    tags: ["project", "inbox"],
    examples: [{
      view_type: "project.inbox",
      content: { items: [{ title: "Review ViewSpec API", reason: "Blocks CLI and processor reporting" }] },
    }],
  },
  {
    view_type: "project.memory",
    title: "Project Memory",
    purpose: "Longer-lived project-specific principles, decisions, constraints, and recurring patterns.",
    lifecycle: "long_term",
    subject: {
      description: "Project identity remains metadata, not a core object.",
      examples: [{ name: "info" }],
    },
    producers: [{ id: "processor.project_memory", kind: "processor" }, { id: "manual.project_memory", kind: "manual" }],
    consumes: {
      views: ["project.decisions", "memory.workflow_patterns"],
      observations: ["feedback.output.edited"],
    },
    default_query: { view_types: ["project.memory"], limit: 20 },
    tags: ["project", "memory"],
    examples: [{
      view_type: "project.memory",
      content: { principles: ["Core owns protocols, not categories."] },
    }],
  },
  {
    view_type: "project.tasks",
    title: "Project Tasks",
    purpose: "Actionable project work items derived from conversations, issues, plans, and agent outputs.",
    lifecycle: "project",
    producers: [{ id: "processor.project_tasks", kind: "processor" }],
    consumes: { views: ["project.current", "project.inbox"], observations: ["observation.codex.message"] },
    default_query: { view_types: ["project.tasks"], limit: 20 },
    tags: ["project", "tasks"],
    examples: [{
      view_type: "project.tasks",
      content: { tasks: [{ title: "Implement mf view CLI", status: "open" }] },
    }],
  },
  {
    view_type: "project.decisions",
    title: "Project Decisions",
    purpose: "Project decisions with rationale, source context, and open consequences.",
    lifecycle: "project",
    producers: [{ id: "processor.project_decision_extractor", kind: "processor" }, { id: "manual.project_decision", kind: "manual" }],
    consumes: { observations: ["observation.codex.message", "observation.claude.message"], views: ["project.current"] },
    default_query: { view_types: ["project.decisions"], limit: 20 },
    tags: ["project", "decisions"],
    examples: [{
      view_type: "project.decisions",
      content: { decisions: [{ title: "Project is a built-in view family, not a kernel object.", confidence: 0.92 }] },
    }],
  },
  {
    view_type: "memory.profile",
    title: "Memory Profile",
    purpose: "High-level retained user model that routes future assistance.",
    lifecycle: "long_term",
    subject: { description: "Open user/profile subject metadata.", examples: [{ type: "user" }] },
    producers: [{ id: "processor.memory_profile_update", kind: "processor" }],
    consumes: { observations: ["feedback.output.edited", "observation.codex.message"], views: ["memory.preferences", "memory.workflow_patterns"] },
    default_query: { view_types: ["memory.profile"], limit: 5 },
    tags: ["memory", "profile"],
    examples: [{ view_type: "memory.profile", content: { summary: "Prefers architecture-first, issue-managed execution." } }],
  },
  {
    view_type: "memory.preferences",
    title: "Memory Preferences",
    purpose: "Stable user preferences that should change future surfacing, routing, and agent behavior.",
    lifecycle: "long_term",
    subject: { description: "Preference subject can be user, project, UI surface, agent, or any open string.", examples: [{ type: "user" }] },
    producers: [{ id: "processor.memory_profile_update", kind: "processor" }, { id: "manual.memory_preference", kind: "manual" }],
    consumes: { observations: ["feedback.view.dismissed", "feedback.output.edited", "observation.codex.message"] },
    default_query: { view_types: ["memory.preferences"], limit: 20 },
    tags: ["memory", "preferences"],
    examples: [{ view_type: "memory.preferences", content: { preference: "Prefer inbox/side-panel over intrusive popups.", confidence: 0.9 } }],
  },
  {
    view_type: "memory.workflow_patterns",
    title: "Memory Workflow Patterns",
    purpose: "Repeated work patterns that future agents can reuse or automate.",
    lifecycle: "long_term",
    subject: { description: "Workflow pattern subject metadata is open.", examples: [{ type: "coding_workflow" }] },
    producers: [{ id: "processor.workflow_pattern_miner", kind: "processor" }],
    consumes: { observations: ["observation.codex.message", "feedback.automation_result"], views: ["automation.outcome", "project.tasks"] },
    default_query: { view_types: ["memory.workflow_patterns"], limit: 20 },
    tags: ["memory", "workflow"],
    examples: [{ view_type: "memory.workflow_patterns", content: { pattern: "Plan with issues, branch, PR, then merge." } }],
  },
  {
    view_type: "memory.skill_gaps",
    title: "Memory Skill Gaps",
    purpose: "Longer-lived areas where the user repeatedly needs support or review.",
    lifecycle: "long_term",
    subject: { description: "Skill or learning subject metadata is open.", examples: [{ type: "language_learning" }] },
    producers: [{ id: "processor.skill_gap_miner", kind: "processor" }],
    consumes: { views: ["learning.review_queue", "learning.youtube_fragment"], observations: ["feedback.review_result"] },
    default_query: { view_types: ["memory.skill_gaps"], limit: 20 },
    tags: ["memory", "learning"],
    examples: [{ view_type: "memory.skill_gaps", content: { skill: "English listening fragments", evidence_count: 4 } }],
  },
  {
    view_type: "memory.agent_collaboration_style",
    title: "Memory Agent Collaboration Style",
    purpose: "How the user wants agents to plan, communicate, ask, and act.",
    lifecycle: "long_term",
    subject: { description: "Agent collaboration subject metadata is open.", examples: [{ type: "agent_collaboration" }] },
    producers: [{ id: "processor.agent_collaboration_style", kind: "processor" }],
    consumes: { observations: ["feedback.output.edited", "observation.codex.message"] },
    default_query: { view_types: ["memory.agent_collaboration_style"], limit: 20 },
    tags: ["memory", "agent"],
    examples: [{ view_type: "memory.agent_collaboration_style", content: { style: "Challenge weak assumptions; keep momentum." } }],
  },
  {
    view_type: "learning.youtube_fragment",
    title: "Learning YouTube Fragment",
    purpose: "Timestamped caption or playback fragment that can become review material.",
    lifecycle: "session",
    subject: { description: "Any video segment; no core enum is required.", examples: [{ type: "video", title: "Agent skills talk" }] },
    producers: [{ id: "processor.youtube_learning", kind: "processor" }],
    consumes: { observations: ["observation.youtube.caption_state", "observation.youtube.caption_fragment"] },
    default_query: { view_types: ["learning.youtube_fragment"], limit: 50 },
    tags: ["learning", "youtube", "scenario"],
    examples: [{ view_type: "learning.youtube_fragment", content: { start_seconds: 120, end_seconds: 146, caption_text: "Example caption text." } }],
  },
  {
    view_type: "writing.advice",
    title: "Writing Advice",
    purpose: "Inline-safe advice for active text editing that can be dismissed or inserted by the user.",
    lifecycle: "ephemeral",
    subject: { description: "Focused editor/input context.", examples: [{ type: "editor", element: "textarea" }] },
    producers: [{ id: "processor.writing_ambient", kind: "processor" }],
    consumes: { observations: ["observation.editor.text_changed"], views: ["state.surface"] },
    default_query: { view_types: ["writing.advice"], limit: 20 },
    tags: ["writing", "scenario"],
    examples: [{ view_type: "writing.advice", content: { advice: "Tighten the second sentence.", action: "insert_optional" } }],
  },
  {
    view_type: "research.brief",
    title: "Research Brief",
    purpose: "Purpose-shaped synthesis from browser pages, selections, and background research.",
    lifecycle: "session",
    subject: { description: "Any research topic/resource subject metadata.", examples: [{ type: "topic", name: "view systems" }] },
    producers: [{ id: "processor.research_brief", kind: "processor" }, { id: "agent.background_research", kind: "agent" }],
    consumes: { observations: ["observation.browser_page_snapshot", "observation.browser_text_selected"], views: ["state.surface"] },
    default_query: { view_types: ["research.brief"], limit: 20 },
    tags: ["research", "scenario"],
    examples: [{ view_type: "research.brief", content: { summary: "Open view registries allow new domains without core schema edits." } }],
  },
];

export function builtinViewSpecs(): ViewSpec[] {
  return [...CORE_VIEW_SPECS];
}
